### ISSUE TITLE
Support BE and BS flags

### ISSUE THREAD

**Issue by jameshartig** [descope/virtualwebauthn#31]
Currently there's no way to set the Backup Eligibility and Backup State flags [1]. We would like to use the authenticator to test our handling of these flags.

[1] https://www.w3.org/TR/webauthn-3/#sctn-authenticator-data

**Comment by shilgapira** [comment]
Hi! Thanks for opening an issue on this.

I'll have time to take a look at this and the other issue within the next few days.

**Comment by shilgapira** [comment]
@zetaab It seems like I adopted a pretty loose definition for `few days`. 🤔

I'll go over this and see if we can integrate it. Thanks for bumping this! 👍

**Comment by zetaab** [comment]
https://github.com/descope/virtualwebauthn/blob/main/utils.go#L45 is perhaps the function that should support those :)

**Comment by zetaab** [comment]
@shilgapira I will make PR for you, just a few minutes.
